### ISSUE TITLE
Ember.js appears multiple times

### ISSUE THREAD

**Issue by NullVoxPopuli** [kaliber5/ember-cli-bundle-analyzer#58]
https://emberclear.io/bundle/broccoli.html

**Comment by NullVoxPopuli** [comment]
if I have broccoli-concat-analyser installed instead of ember-cli-bundle-analyzer, how do I get the fix? ;)

**Comment by NullVoxPopuli** [comment]
can ember-cli-bundle-analyzer be invoked via CLI?

**Comment by NullVoxPopuli** [comment]
my use case: 

GH action:
```yaml
  bundle_analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: rwjblue/setup-volta@v1

    - name: Install
      working-directory: ${{ env.cwd }}
      run: yarn install

    - name: Analyze Bundle
      working-directory: ${{ env.cwd }}
      run: yarn analyze
      # ^ this runs the script below

    - name: Upload Bundle Analysis Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: built_bundle_analysis
        path: packages/frontend/public/bundle

```
(the artifacts are then downloaded later and merged with the regular app build during deployment)

```bash
#!/bin/bash
# yarn analyze runs this

R="\e[31m"
Y="\e[33m"
N="\e[0m"

# outputs the following files:
# - concats-stats-for/
#   - #-emberclear.js.json
#   - #-vendor.js.json
#   - #-vendor.css.json
#   - ember-auto-import.json
#
rm -rf public/bundle
# ember-auto-import.json was not a part of
# broccoli-concat-analyzer, so that file needs
# to be stitched into the index.html file
CONCAT_STATS=true yarn build:production



# begin analysis
yarn bundle-analyze
# alias for:
# "bundle-analyze": "yarn broccoli-concat-analyser ./concat-stats-for",


# copy to public folder for deployment
mkdir -p ./public/bundle
cp ./concat-stats-for/index.html ./public/bundle/broccoli.html
cp ./concat-stats-for/ember-auto-import.html ./public/bundle/
# copy from dist to public, because we build one more time without CONCAT_STATS
cp ./dist/bundle/* ./public/bundle/
```
